title = "Interpretando o GPT"
baseURL = "https://impact-rio.github.io/mech-interp-course"

languageCode = "pt-BR"
defaultContentLanguage = "pt"

enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
